# Generated by Django 4.2.4 on 2023-08-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('currency', models.CharField(choices=[('KG', 'KG'), ('USD', 'USD'), ('EU', 'EU'), ('RU', 'RU')], default='KG', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуальна ли?')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100, verbose_name='Тэг')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=100, verbose_name='Product')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запись создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Запись обновлена')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.category', verbose_name='Категория')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='product.price')),
                ('tags', models.ManyToManyField(null=True, to='product.tags')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name_of_product',),
            },
        ),
    ]
